#+TITLE: Android 开发
#+AUTHOR: 褚 旭
#+email: chuxubank@gmail.com

#+MOBILE: (+86) 18516704081
#+HOMEPAGE: blog.chuxubank.top
#+GITHUB: chuxubank
#+LINKEDIN: chuxubank
#+PHOTO: photo.jpg

* Employement
:PROPERTIES:
:CV_ENV:   cventries
:END:

** Android 开发
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2020-01-05 Mon>
:TO:       Now
:LOCATION: 中国，上海
:EMPLOYER: 亚萨合莱（中国）投资有限公司上海分公司
:END:

- 负责用 Jetpack Compose 重新开发电子锁的设置流程，自定义 ExoPlayer 播放控件并与 Compose 整合，简化电子锁绑定流程。
  在 All-Hands Meeting 上对全球同事进行展示。
- 

** Android 开发
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2019-12-01 Mon>
:TO:       <2021-10-21 Thu>
:LOCATION: 中国，上海
:EMPLOYER: 上海致研智能有限公司
:END:

- 使用 Java 实现 C/S 架构的图书盘点系统的 Android 客户端部分，与 RFID 扫描枪通过蓝牙连接完成图书馆内的图书盘点，并在客户端 实现书籍索书号的排序算法。使用 Docker 改进盘点服务器部署流程，加快公司发货速度。
- 维护 Java 实现的双开门 RFID 图书自助借还柜，在保持功能不变的情况下精简并美化代码，修复多处 BUG。增加了通过智能中央控制系统远程修改设备配置以及软硬件重启的功能。
- 使用 Crypto++ 开发公司的授权控制库，使用 CMake 进行构建。
- 使用 Kotlin 实现人脸注册机，借助 Google 的 MLKit 和 CameraX 实现识别到人脸且角度合适时抓拍照片并裁切人脸部分区域进行注册，与通过 HID 设备识别出的卡号进行绑定，实现闸机上人脸和刷卡均可通行。
- 充分利用 Android Jetpack 架构组件和 Hilt 依赖注入库，结合 Retrofit2, Moshi, Coil‐kt, Coroutines, Flow 完成网络请求和图片缓存，开发了一款在线和离线均可使用的电子书阅读应用。图书管理员可自由通过 XLSX 文件和 ZIP 文件添加图书信息和图书内容(支持 PDF 和 EPUB 两种格式)。
- 使用 Jetpack Compose 框架开发图书自助借还机，通过扫描微信读者证二维码读者即可自助完成图书借还。对 Android 的串口通信库使用 Kotlin 协程进行了二次封装，同时支持 USB 串口和 RS‐232/485 串口的通信。

** Android 开发（实习）
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2019-04-01 Mon>
:TO:       <2019-08-01 Thu>
:LOCATION: 中国，上海
:EMPLOYER: 上海西派埃智能化系统有限公司
:END:

- 负责移动端 NFC 读写工具的开发，使用 Retrofit 和 Realm 进行网络请求和数据持久化，并与手机 NFC 组件交互，进行 NFC 标签的读写。
- 使用 PersistentCookieJar 读取并存储 Cookie 信息,保持用户登录。
  + 在使用该库时发现其 Cookie 数据验证与公司提供的不符合,并通过 Java 重写机制修复了此问题。

