name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  emacs-batch:
    runs-on: ubuntu-latest
    container:
      image: chuxubank/cat-emacs
      volumes:
        - ${{ github.workspace }}/org:/root/org
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "org"

      - name: Checking directory
        run: ls -al /root/.emacs.d/elpa

      - name: Run Emacs Commands
        run: |
          emacs -batch -eval '(progn
          (package-initialize)
          (message "%s" package-directory-list)
          (require 'org-agenda)
          (setq org-agenda-custom-commands
            (quote (("X" agenda "" nil ("agenda.html")))))
          (org-batch-store-agenda-views
            org-agenda-include-diary nil
            org-directory "/root/org"
            org-agenda-files (list "inbox.org")))'
