name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  emacs-batch:
    runs-on: ubuntu-latest
    container:
      image: chuxubank/cat-emacs
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checking directory
        run: echo "$HOME"

      - name: Run Emacs Commands
        run: |
          emacs -batch --user=root -l batch/agenda.el -eval '(org-batch-store-agenda-views
            org-agenda-include-diary nil
            org-directory "${{ github.workspace }}"
            org-agenda-files (list "inbox.org"))'
