name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  emacs-batch:
    runs-on: ubuntu-latest
    container:
      image: chuxubank/cat-emacs
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "org"

      - name: Run Emacs Commands
        run: |
          emacs -batch -l org/batch/agenda.el -eval '(org-batch-store-agenda-views
            org-agenda-include-diary nil
            org-agenda-files (list "${{ github.workspace }}/org/inbox.org"))'
