name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOME: ${{ github.workspace }}
      ORG_DIR: ${{ github.workspace }}/org
      TZ: Asia/Shanghai
    container:
      image: chuxubank/cat-emacs
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "org"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Check timezone
        run: emacs -batch --eval '(message "%s" (current-time-zone))'

      - name: Check container id and home
        run: id && echo $HOME

      - name: Checking org version
        run: emacs -batch -f org-version

      - name: Make publish dir
        run: mkdir -p publish

      - name: Move assets
        run: mv $ORG_DIR/assets/ publish/

      - name: Run Emacs Commands
        run: script -q -c "emacs -q -l $ORG_DIR/batch/agenda.el -eval '(org-batch-store-agenda-views)' -kill"
        env:
          TERM: xterm-256color

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
