name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  emacs-batch:
    runs-on: ubuntu-latest
    env:
      HOME: /root
      ORG_DIR: /root/org
    container:
      image: chuxubank/cat-emacs
      volumes:
        - ${{ github.workspace }}/org:/root/org
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "org"

      - name: Checking org version
        run: |
          emacs -batch -f org-version

      - name: Checking directory
        run: echo "$HOME"; ls -al $HOME/.emacs.d/elpa

      - name: Run Emacs Commands
        run: |
          emacs -batch -l org/batch/agenda.el -eval '(org-batch-store-agenda-views)'
