name: Org Agenda Batch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  emacs-batch:
    runs-on: ubuntu-latest
    container:
      image: chuxubank/cat-emacs
      volumes:
        - ${{ github.workspace }}/org:/root/org
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "org"

      - name: Checking directory
        run: ls -al; pwd; ls -al org; cd ..; pwd

      - name: Run Emacs Commands
        run: |
          emacs -batch -l org/batch/agenda.el -eval '(org-batch-store-agenda-views
            org-agenda-include-diary nil
            org-agenda-files (list "inbox.org"))'
